name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Auto build
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        sh deploy.sh
